version: "3.9"
services:
  gg-minecraft-api:
    build: .
    ports:
      - 80:8080
    volumes:
      - ./config/:/go/gambitdev/gg-minecraft-api/build/config/
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
