version: "3.3"
services:
  gg-minecraft-api:
    build:
      context: ./
      dockerfile: ./Server.Dockerfile
    image: gambitdev/bedgg-minecraft-api:latest
    #ports:
    #  - "0.0.0.0:80:8080"
    #depends_on:
    #  - redis
    network_mode: host

#  profile-scanner:
#    build:
#      context: ./
#      dockerfile: ./Scanner.Dockerfile
#    image: gambitdev/bedgg-profile-scanner:latest
#    depends_on:
#      - profile-store
#      - meilisearch
#  profile-store:
#    build:
#      context: ./
#      dockerfile: ./Store.Dockerfile
#    image: gambitdev/bedgg-profile-store:latest
#    ports:
#      - "3000:8080"
#    depends_on:
#      - redis-store
  redis:
    image: redis
    ports:
      - "6379:6379"
#  redis-store:
#    image: redis
#    ports:
#      - "6380:6379"
#  meilisearch:
#    image: getmeili/meilisearch:latest
#    volumes:
#      - ./data/meilisearch/:/meili_data/
#    ports:
#      - "7700:7700"

# networks:
#   gg-network:
#     driver: ipvlan
#     driver_opts:
#       parent: eth0
#     ipam:
#       config:
#         - subnet: 10.0.0.0/24
#           gateway: 10.0.0.254