version: "3.3"
services:
  gg-minecraft-api:
    build: ./profile-server
    image: gambitdev/bedgg-minecraft-api:latest
    ports:
      - 80:8080
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
